TRUNCATE TABLE venue_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE venue_supported_music RESTART IDENTITY CASCADE;
TRUNCATE TABLE venues RESTART IDENTITY CASCADE;

INSERT INTO venues
(id,name,average_price,crowded,capacity,dj_performance,
 private_tables,premium_service,outdoor_seating,
 quality_food,games_available,sports_streaming,
 noise_level,social_level,atmosphere_level,
 comfort_level,service_level)

VALUES
    (1,'Moonlight Lounge',12,false,80,false,true,false,true,true,false,false,2,6,9,9,6),
    (2,'Sky Lounge',45,false,120,true,true,true,true,true,false,false,2,8,10,10,10),
    (3,'Jazz Garden',25,false,90,false,true,false,true,true,false,false,3,6,9,8,8),
    (4,'Student Pub',8,true,250,false,false,false,false,false,true,true,8,9,5,5,5),
    (5,'Beer Factory',14,true,300,false,false,false,false,false,true,true,7,9,5,5,5),
    (6,'Royal Restaurant',65,false,100,false,true,true,false,true,false,false,2,7,10,10,10),
    (7,'River Terrace',28,false,110,false,true,false,true,true,false,false,3,5,9,8,8),
    (8,'Techno Club X',18,true,600,true,false,false,false,false,false,false,10,10,7,4,5),
    (9,'Bella Vista',42,false,90,false,true,true,true,true,false,false,2,5,10,9,9),
    (10,'Game House',15,true,180,false,false,false,false,false,true,false,6,8,6,6,6),
    (11,'Elite Club',75,false,180,true,true,true,false,true,false,false,4,9,10,9,10),
    (12,'Green Garden',20,false,70,false,false,false,true,true,false,false,2,4,8,8,7),
    (13,'Sports Corner',16,true,220,false,false,false,false,false,false,true,7,8,5,5,5),
    (14,'Acoustic Nights',30,false,100,false,true,false,true,true,false,false,3,5,9,8,8),
    (15,'Sunset Terrace',35,false,120,false,true,false,true,true,false,false,2,5,9,9,8),
    (16,'City Rooftop',55,false,150,true,true,true,true,true,false,false,3,8,10,9,9),
    (17,'Live Stage',22,true,400,false,false,false,false,false,false,false,8,9,7,6,6),
    (18,'Karaoke Box',18,true,140,false,false,false,false,false,true,false,7,8,6,5,5),
    (19,'Quiet Corner',14,false,40,false,false,false,false,true,false,false,1,3,8,8,7),
    (20,'Prestige Hall',85,false,220,true,true,true,false,true,false,false,2,7,10,10,10),
    (21,'Rock Station',20,true,350,false,false,false,false,false,false,false,8,8,7,6,6),
    (22,'Folk Tavern',17,false,100,false,false,false,true,true,false,false,3,5,8,7,7),
    (23,'Blue Note Bar',27,false,90,false,true,false,false,true,false,false,4,6,9,8,8),
    (24,'Golden Garden',40,false,130,false,true,true,true,true,false,false,2,5,9,9,9),
    (25,'Party Factory',18,true,500,true,false,false,false,false,true,false,9,10,7,5,5),
    (26,'Retro Club',24,true,280,true,false,false,false,false,false,false,8,9,6,5,6),
    (27,'Wine House',50,false,70,false,true,true,false,true,false,false,2,4,10,10,9),
    (28,'The Hideout',22,false,85,false,true,false,true,true,true,false,3,6,8,8,8),
    (29,'Arena Pub',19,true,320,false,false,false,false,false,true,true,7,9,6,5,5),
    (30,'Harmony Lounge',38,false,95,false,true,true,true,true,false,false,2,5,10,9,9);

INSERT INTO venue_supported_music (venue_id,supported_music) VALUES
                                                                 (1,'JAZZ'),
                                                                 (1,'FOLK'),
                                                                 (2,'POP'),
                                                                 (2,'JAZZ'),
                                                                 (2,'FOLK'),
                                                                 (3,'JAZZ'),
                                                                 (3,'FOLK'),
                                                                 (4,'ROCK'),
                                                                 (4,'POP'),
                                                                 (5,'ROCK'),
                                                                 (5,'POP'),
                                                                 (5,'FOLK'),
                                                                 (6,'JAZZ'),
                                                                 (6,'POP'),
                                                                 (7,'FOLK'),
                                                                 (7,'JAZZ'),
                                                                 (8,'TECHNO'),
                                                                 (9,'POP'),
                                                                 (9,'JAZZ'),
                                                                 (10,'ROCK'),
                                                                 (10,'POP'),
                                                                 (11,'TECHNO'),
                                                                 (11,'POP'),
                                                                 (11,'ROCK'),
                                                                 (12,'JAZZ'),
                                                                 (12,'FOLK'),
                                                                 (13,'ROCK'),
                                                                 (13,'POP'),
                                                                 (14,'FOLK'),
                                                                 (14,'JAZZ'),
                                                                 (14,'POP'),
                                                                 (15,'JAZZ'),
                                                                 (15,'POP'),
                                                                 (16,'TECHNO'),
                                                                 (16,'POP'),
                                                                 (16,'JAZZ'),
                                                                 (17,'ROCK'),
                                                                 (17,'TECHNO'),
                                                                 (18,'POP'),
                                                                 (18,'FOLK'),
                                                                 (19,'JAZZ'),
                                                                 (20,'TECHNO'),
                                                                 (20,'JAZZ'),
                                                                 (20,'POP'),
                                                                 (21,'ROCK'),
                                                                 (21,'POP'),
                                                                 (22,'FOLK'),
                                                                 (22,'JAZZ'),
                                                                 (23,'JAZZ'),
                                                                 (23,'POP'),
                                                                 (24,'POP'),
                                                                 (24,'JAZZ'),
                                                                 (24,'FOLK'),
                                                                 (25,'TECHNO'),
                                                                 (25,'POP'),
                                                                 (26,'TECHNO'),
                                                                 (26,'ROCK'),
                                                                 (27,'JAZZ'),
                                                                 (28,'FOLK'),
                                                                 (28,'POP'),
                                                                 (29,'ROCK'),
                                                                 (29,'POP'),
                                                                 (30,'JAZZ'),
                                                                 (30,'POP'),
                                                                 (30,'FOLK');

INSERT INTO venue_events (venue_id,events) VALUES
                                               (1,'ACOUSTIC'),
                                               (2,'DJ'),
                                               (2,'LIVE_BAND'),
                                               (3,'LIVE_BAND'),
                                               (3,'ACOUSTIC'),
                                               (4,'KARAOKE'),
                                               (5,'DJ'),
                                               (5,'KARAOKE'),
                                               (6,'LIVE_BAND'),
                                               (7,'ACOUSTIC'),
                                               (8,'DJ'),
                                               (9,'LIVE_BAND'),
                                               (9,'ACOUSTIC'),
                                               (10,'KARAOKE'),
                                               (10,'DJ'),
                                               (11,'DJ'),
                                               (11,'LIVE_BAND'),
                                               (11,'ACOUSTIC'),
                                               (12,'ACOUSTIC'),
                                               (13,'DJ'),
                                               (14,'ACOUSTIC'),
                                               (14,'LIVE_BAND'),
                                               (15,'LIVE_BAND'),
                                               (16,'DJ'),
                                               (16,'LIVE_BAND'),
                                               (17,'LIVE_BAND'),
                                               (17,'DJ'),
                                               (18,'KARAOKE'),
                                               (18,'DJ'),
                                               (19,'ACOUSTIC'),
                                               (20,'DJ'),
                                               (20,'LIVE_BAND'),
                                               (20,'ACOUSTIC'),
                                               (21,'LIVE_BAND'),
                                               (22,'ACOUSTIC'),
                                               (23,'LIVE_BAND'),
                                               (23,'ACOUSTIC'),
                                               (24,'LIVE_BAND'),
                                               (25,'DJ'),
                                               (25,'KARAOKE'),
                                               (26,'DJ'),
                                               (27,'ACOUSTIC'),
                                               (28,'KARAOKE'),
                                               (29,'DJ'),
                                               (29,'LIVE_BAND'),
                                               (30,'ACOUSTIC'),
                                               (30,'LIVE_BAND');